# Generated by Django 4.1.7 on 2023-03-14 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0002_food_rabbit'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='rabbit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='snacks.rabbit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rabbit',
            name='foods',
            field=models.ManyToManyField(related_name='foods', to='snacks.food'),
        ),
    ]
