# Generated by Django 4.1.7 on 2023-03-14 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0003_food_rabbit_rabbit_foods'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='rabbit',
        ),
    ]
