# Generated by Django 4.1.7 on 2023-03-16 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0005_rabbit_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rabbit',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rabbits', to=settings.AUTH_USER_MODEL),
        ),
    ]
